### ISSUE TITLE
Can't turn debugging off when website runs on port different than 80

### ISSUE THREAD

**Issue by mleczakm** [kudlatyamroth/xdebug-session-cookie#2]
Icon don't change when debugging address with port, for example on 8000 or 8080 port, also status is not updated so can't turn debugging off (cookie is added).

I've prepared some dirty hack to have icon properly working  #1.

Firefox dev edition, 57.0b1 (64-bit)

**Comment by advancingu** [comment]
@kudlatyamroth Any plans to get this merged? The extension is not very useful at the moment without the fix in #1.

**Comment by kudlatyamroth** [comment]
Hi, sorry but i don't received notification about this...
Merged and uploaded to AMO, waiting for Mozilla review

**Comment by advancingu** [comment]
:+1: Received the update today. Thanks.
