### ISSUE TITLE
The plugin does not work in private mode

### ISSUE THREAD

**Issue by serhiiko** [kudlatyamroth/xdebug-session-cookie#3]
Hello. When using private browsing, the debug cookie is not added to the query.

**Comment by piRGoif** [comment]
Same when using Firefox Multi-Account Containers (https://addons.mozilla.org/fr/firefox/addon/multi-account-containers/)...

**Comment by StoyanDimitrov** [comment]
Same with first-party isolation enabled, just for completeness.

**Comment by kudlatyamroth** [comment]
Now it should work in private browsing and multi account containers.

First-party isolation is not working for some reason. So for this reason i created issue #4
